lang: cpp

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt551
  - sudo apt-get update
  - sudo apt-get -y install qt55declarative qt55tools libpam0g-dev

before_script:
  # cmake
  - wget --no-check-certificate http://www.cmake.org/files/v3.3/cmake-3.3.0-Linux-x86_64.tar.gz -O cmake.tar.gz
  - tar -xzf cmake.tar.gz -C $HOME
  - export PATH=$HOME/cmake-3.3.0-Linux-x86_64/bin:$PATH
  - cmake --version
  # e-c-m
  - wget --no-check-certificate http://download.kde.org/stable/frameworks/5.12/extra-cmake-modules-5.12.0.tar.xz
  - tar -xJf extra-cmake-modules-5.12.0.tar.xz
  - pushd extra-cmake-modules-5.12.0
  - rm -rf build
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/ecm
  - make && make install
  - popd
  - export PATH=$HOME/ecm/bin:$PATH
  # prepare
  - source /opt/qt55/bin/qt55-env.sh
  - echo $PATH
  - mkdir build
  - cd build
  - cmake ..

script: make
